# Generated by Django 4.0.10 on 2026-08-20 08:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_json_field_schema_validator.validators
import courses.mixins
import courses.models
import courses.validators
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courseteams", "__first__"),
        ("bookmarks", "__first__"),
        ("moduletypes", "__first__"),
        ("preferences", "__first__"),
        ("tags", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "hrdb_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Identifier in HRDB",
                        null=True,
                        unique=True,
                        verbose_name="HRDB ID",
                    ),
                ),
                (
                    "begin_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="study start",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="study end",
                    ),
                ),
                (
                    "enroll_begin",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="enrollment start",
                    ),
                ),
                (
                    "enroll_end",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="enrollment end",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Full price requested by the provider",
                        max_digits=10,
                        null=True,
                        verbose_name="catalog price",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("corporate", "Company-funded"),
                            ("personal", "Payroll deduction"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "paid_percent",
                    models.IntegerField(
                        default=0,
                        help_text="Relevant only when the employee pays",
                        verbose_name="deduction percentage",
                    ),
                ),
                (
                    "payment_terms",
                    models.TextField(
                        blank=True,
                        help_text="Description of payment terms, deductions, and company cost",
                        verbose_name="payment terms",
                    ),
                ),
                (
                    "estimated_time",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="minutes",
                        null=True,
                        verbose_name="completion time",
                    ),
                ),
                (
                    "enable_groups",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="Has student groups",
                    ),
                ),
                (
                    "enable_followers",
                    models.BooleanField(
                        default=False,
                        help_text="all course subscriptions are allowed",
                        verbose_name="allow course subscriptions",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255,
                        unique=True,
                        validators=[courses.validators.validate_course_slug],
                        verbose_name="code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="short name"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=2048, verbose_name="summary"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "target_audience_description",
                    models.TextField(
                        blank=True, default="", verbose_name="target audience"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, max_length=500, verbose_name="cover"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="active"),
                ),
                (
                    "is_archive",
                    models.BooleanField(default=False, verbose_name="archived"),
                ),
                (
                    "calc_begin_date",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="actual study start",
                    ),
                ),
                (
                    "calc_end_date",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="actual study end",
                    ),
                ),
                (
                    "calc_enroll_begin",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="actual enrollment start",
                    ),
                ),
                (
                    "calc_enroll_end",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="actual enrollment end",
                    ),
                ),
                (
                    "structure",
                    models.CharField(
                        choices=[
                            ("no_modules", "No modules"),
                            ("single_module", "Single module"),
                            ("multi_modules", "Multiple modules"),
                        ],
                        default="no_modules",
                        max_length=20,
                        verbose_name="course structure",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("self_study", "Self-paced"),
                            ("with_teacher", "Instructor-led"),
                        ],
                        max_length=20,
                        verbose_name="study format",
                    ),
                ),
                (
                    "retries_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="After completing the course, the user can enroll again and retake it",
                        verbose_name="course retake",
                    ),
                ),
                (
                    "completion_threshold",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Completion percentage required to finish the course",
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="completion threshold",
                    ),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("track", "Program"),
                            ("other", "Other"),
                        ],
                        default="course",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "description_version",
                    models.IntegerField(choices=[(1, "Old"), (2, "New")], default=1),
                ),
                (
                    "start_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("any_time", "Any time"),
                            ("after_group_filled", "After the cohort is filled"),
                            ("fixed_dates", "Fixed date"),
                        ],
                        default="any_time",
                        max_length=30,
                        null=True,
                        verbose_name="start mode",
                    ),
                ),
                (
                    "is_audit",
                    models.BooleanField(default=False, verbose_name="auditable"),
                ),
                (
                    "rating",
                    models.FloatField(blank=True, null=True, verbose_name="rating"),
                ),
                (
                    "number_ratings",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="number of ratings"
                    ),
                ),
                (
                    "migrated_to_avatars",
                    models.BooleanField(
                        default=True, verbose_name="migrated to Avatars"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
                "ordering": ("name",),
                "permissions": (
                    ("import_course", "Can import courses"),
                    ("export_course", "Can export courses"),
                    ("enroll_to_course", "Can enroll to courses"),
                ),
            },
            bases=(courses.mixins.AvailabilityMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CourseBlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=2048, verbose_name="short description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blocks",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "course block",
                "verbose_name_plural": "course blocks",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CourseGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "hrdb_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Identifier in HRDB",
                        null=True,
                        unique=True,
                        verbose_name="HRDB ID",
                    ),
                ),
                (
                    "begin_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="study start",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="study end",
                    ),
                ),
                (
                    "enroll_begin",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="enrollment start",
                    ),
                ),
                (
                    "enroll_end",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="enrollment end",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Full price requested by the provider",
                        max_digits=10,
                        null=True,
                        verbose_name="catalog price",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("corporate", "Company-funded"),
                            ("personal", "Payroll deduction"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "paid_percent",
                    models.IntegerField(
                        default=0,
                        help_text="Relevant only when the employee pays",
                        verbose_name="deduction percentage",
                    ),
                ),
                (
                    "payment_terms",
                    models.TextField(
                        blank=True,
                        help_text="Description of payment terms, deductions, and company cost",
                        verbose_name="payment terms",
                    ),
                ),
                (
                    "estimated_time",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="minutes",
                        null=True,
                        verbose_name="completion time",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, verbose_name="code"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=2048, verbose_name="short description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active"),
                ),
                (
                    "can_join",
                    models.BooleanField(
                        default=True, verbose_name="enrollment allowed"
                    ),
                ),
                (
                    "num_participants",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="number of participants"
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=0, verbose_name="maximum number of participants"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="group",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="participants",
                    ),
                ),
            ],
            options={
                "verbose_name": "student group",
                "verbose_name_plural": "student groups",
                "ordering": ("begin_date", "name"),
                "permissions": (
                    ("import_coursegroup", "Can import course groups"),
                    ("export_coursegroup", "Can export course groups"),
                ),
            },
            bases=(courses.mixins.AvailabilityMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CourseModule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active"),
                ),
                (
                    "estimated_time",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="estimated course completion time (minutes)",
                        null=True,
                        verbose_name="estimated completion time",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="weight",
                    ),
                ),
                (
                    "weight_scaled",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="calculated automatically from the weights of all course modules",
                        max_digits=3,
                        validators=[
                            django.core.validators.MaxValueValidator(1),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="absolute weight share",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modules",
                        to="courses.courseblock",
                        verbose_name="block",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modules",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "module_type",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modules",
                        to="moduletypes.moduletype",
                        verbose_name="module type",
                    ),
                ),
            ],
            options={
                "verbose_name": "course module",
                "verbose_name_plural": "course modules",
                "ordering": ("block__order", "order"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CourseStudent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="course completion date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expelled", "Expelled"),
                            ("completed", "Completed training"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "substatus",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("education_canceled", "education cancelled"),
                            ("study_interrupted", "study interrupted"),
                            ("dismissed", "dismissed"),
                            ("success", "successful"),
                            ("failure", "unsuccessful"),
                        ],
                        max_length=20,
                        verbose_name="substatus",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the user has hidden the course",
                        verbose_name="Visibility",
                    ),
                ),
                (
                    "is_passed",
                    models.BooleanField(
                        default=False, verbose_name="passing score achieved"
                    ),
                ),
                (
                    "passing_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="time when the student achieved the passing score",
                        null=True,
                        verbose_name="course completion date",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="is mandatory"),
                ),
                (
                    "required_since",
                    models.DateTimeField(
                        blank=True,
                        help_text="time when the course became mandatory for the student",
                        null=True,
                        verbose_name="course assignment date",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="courses.coursegroup",
                        verbose_name="group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "student",
                "verbose_name_plural": "students",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="StudyMode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="code"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "study mode",
                "verbose_name_plural": "study modes",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CourseProgram",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="program",
                        serialize=False,
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "program",
                    models.JSONField(
                        default=courses.models.get_default_program,
                        validators=[
                            django_json_field_schema_validator.validators.JSONFieldSchemaValidator(
                                schema={
                                    "additionalProperties": False,
                                    "definitions": {
                                        "module_schema": {
                                            "additionalProperties": False,
                                            "properties": {
                                                "hours": {
                                                    "minimum": 0,
                                                    "type": "number",
                                                },
                                                "minutes": {
                                                    "maximum": 59,
                                                    "minimum": 0,
                                                    "type": "number",
                                                },
                                                "title": {
                                                    "maxLength": 255,
                                                    "type": "string",
                                                },
                                            },
                                            "required": ["title"],
                                            "type": "object",
                                        }
                                    },
                                    "oneOf": [
                                        {"required": ["group_blocks", "blocks"]},
                                        {"required": ["group_blocks", "modules"]},
                                    ],
                                    "properties": {
                                        "blocks": {
                                            "items": {
                                                "additionalProperties": False,
                                                "properties": {
                                                    "modules": {
                                                        "items": {
                                                            "$ref": "#/definitions/module_schema"
                                                        },
                                                        "type": "array",
                                                    },
                                                    "title": {
                                                        "maxLength": 255,
                                                        "type": "string",
                                                    },
                                                },
                                                "required": ["title", "modules"],
                                                "type": "object",
                                            },
                                            "type": "array",
                                        },
                                        "group_blocks": {"type": "boolean"},
                                        "modules": {
                                            "items": {
                                                "$ref": "#/definitions/module_schema"
                                            },
                                            "type": "array",
                                        },
                                    },
                                    "type": "object",
                                }
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Course program",
                "verbose_name_plural": "Course programs",
            },
        ),
        migrations.CreateModel(
            name="CourseTutor",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="tutor",
                        serialize=False,
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "hide",
                    models.BooleanField(
                        default=False,
                        help_text="do not show on the course card",
                        verbose_name="hide",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course curator",
                "verbose_name_plural": "Course curators",
            },
        ),
        migrations.CreateModel(
            name="StudentModuleProgress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="scores",
                    ),
                ),
                (
                    "score_scaled",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="weighted scores",
                    ),
                ),
                (
                    "passing_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="module completion date"
                    ),
                ),
                (
                    "is_set_attendance",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="attendance recorded"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="module_progresses",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progresses",
                        to="courses.coursemodule",
                        verbose_name="module",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="module_progresses",
                        to="courses.coursestudent",
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "module progress",
                "verbose_name_plural": "module progress records",
            },
        ),
        migrations.CreateModel(
            name="StudentCourseState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "last_visited_module",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Last opened module"
                    ),
                ),
                (
                    "state",
                    models.JSONField(blank=True, default=dict, verbose_name="State"),
                ),
                (
                    "cache",
                    models.JSONField(blank=True, default=dict, verbose_name="Cache"),
                ),
                (
                    "complete_all_modules_modal_shown",
                    models.CharField(
                        choices=[
                            ("disabled", "Disabled"),
                            ("enabled", "Enabled"),
                            ("completed", "Completed"),
                        ],
                        default="disabled",
                        max_length=20,
                        verbose_name="Course completion dialog status",
                    ),
                ),
                (
                    "need_ask_language",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Need to ask for the study language",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_course_states",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_course_state",
                        to="courses.coursestudent",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course completion state",
                "verbose_name_plural": "Course completion states",
            },
        ),
        migrations.CreateModel(
            name="StudentCourseProgress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="scores",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_progresses",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_progresses",
                        to="courses.coursestudent",
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "course progress",
                "verbose_name_plural": "course progress records",
            },
        ),
        migrations.CreateModel(
            name="HistoricalStudentCourseProgress",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="scores",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical course progress",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCourseStudent",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="course completion date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expelled", "Expelled"),
                            ("completed", "Completed training"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "substatus",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("education_canceled", "education cancelled"),
                            ("study_interrupted", "study interrupted"),
                            ("dismissed", "dismissed"),
                            ("success", "successful"),
                            ("failure", "unsuccessful"),
                        ],
                        max_length=20,
                        verbose_name="substatus",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the user has hidden the course",
                        verbose_name="Visibility",
                    ),
                ),
                (
                    "is_passed",
                    models.BooleanField(
                        default=False, verbose_name="passing score achieved"
                    ),
                ),
                (
                    "passing_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="time when the student achieved the passing score",
                        null=True,
                        verbose_name="course completion date",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="is mandatory"),
                ),
                (
                    "required_since",
                    models.DateTimeField(
                        blank=True,
                        help_text="time when the course became mandatory for the student",
                        null=True,
                        verbose_name="course assignment date",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="courses.coursegroup",
                        verbose_name="group",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical student",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCourseGroup",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "hrdb_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Identifier in HRDB",
                        null=True,
                        verbose_name="HRDB ID",
                    ),
                ),
                (
                    "begin_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="study start",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="study end",
                    ),
                ),
                (
                    "enroll_begin",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="enrollment start",
                    ),
                ),
                (
                    "enroll_end",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="enrollment end",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Full price requested by the provider",
                        max_digits=10,
                        null=True,
                        verbose_name="catalog price",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("corporate", "Company-funded"),
                            ("personal", "Payroll deduction"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "paid_percent",
                    models.IntegerField(
                        default=0,
                        help_text="Relevant only when the employee pays",
                        verbose_name="deduction percentage",
                    ),
                ),
                (
                    "payment_terms",
                    models.TextField(
                        blank=True,
                        help_text="Description of payment terms, deductions, and company cost",
                        verbose_name="payment terms",
                    ),
                ),
                (
                    "estimated_time",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="minutes",
                        null=True,
                        verbose_name="completion time",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, verbose_name="code"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=2048, verbose_name="short description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active"),
                ),
                (
                    "can_join",
                    models.BooleanField(
                        default=True, verbose_name="enrollment allowed"
                    ),
                ),
                (
                    "num_participants",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="number of participants"
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=0, verbose_name="maximum number of participants"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical student group",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CourseTeacher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "role",
                    models.CharField(blank=True, max_length=255, verbose_name="role"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_teachers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="instructor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instructor, presenter, or other",
                "verbose_name_plural": "Instructors, presenters, and others",
            },
        ),
        migrations.CreateModel(
            name="CourseOccupancy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "current",
                    models.PositiveIntegerField(default=0, verbose_name="current"),
                ),
                (
                    "maximum",
                    models.PositiveIntegerField(default=0, verbose_name="maximum"),
                ),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupancy",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "course capacity",
                "verbose_name_plural": "course capacity",
            },
        ),
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="code"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active"),
                ),
                (
                    "color_theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="preferences.colortheme",
                        verbose_name="color scheme",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_course_categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="courses.coursecategory",
                        verbose_name="Parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "course category",
                "verbose_name_plural": "course categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CourseBookmark",
            fields=[
                (
                    "bookmark_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bookmarks.bookmark",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bookmarks: Course",
                "verbose_name_plural": "Bookmarks: Courses",
            },
            bases=("bookmarks.bookmark", models.Model),
        ),
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                to="courses.coursecategory",
                verbose_name="categories",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="study_mode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="courses.studymode",
                verbose_name="study mode",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="tags.tag", verbose_name="tags"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="teams",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                to="courseteams.courseteam",
                verbose_name="course teams",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentmoduleprogress",
            constraint=models.UniqueConstraint(
                fields=("student", "module"), name="unique_student_module"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentcourseprogress",
            constraint=models.UniqueConstraint(
                fields=("student", "course"), name="unique_student_course"
            ),
        ),
        migrations.AddField(
            model_name="coursetutor",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_tutor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="curator",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursebookmark",
            constraint=models.UniqueConstraint(
                fields=("created_by", "course"), name="unique_course_bookmark_per_user"
            ),
        ),
    ]
